#!/usr/bin/env node
/* ===========================================================
   Drakkhak — rewrite the script tags in index.html.

       node tools/build-index.js

   Lists every content file (js/data, the top level of js/gen) and every
   engine file in the order the app needs them, writes them between the
   SCRIPTS markers, and bumps the ?v= cache number so browsers fetch the
   new files. Run it after adding or removing any .js file.

   js/gen/spare/ is skipped on purpose: those are the maths families kept
   from the IBA/GRE edition, waiting to be adapted for Higher Math and
   Physics numericals. Move a file up into js/gen/ to ship it.
   =========================================================== */
'use strict';
var fs=require('fs'), path=require('path');
var ROOT=path.join(__dirname,'..');
var html=fs.readFileSync(path.join(ROOT,'index.html'),'utf8');

var m=html.match(/\?v=(\d+)"/);
var v=(m?parseInt(m[1],10):0)+1;

function list(dir, skip){
  return fs.readdirSync(path.join(ROOT,dir))
    .filter(function(f){ return /\.js$/.test(f) && (skip||[]).indexOf(f)<0; })
    .sort().map(function(f){ return dir+'/'+f; });
}
/* the Bangla faces are part of the app, not a CDN's problem */
var FONTS=fs.readdirSync(path.join(ROOT,'fonts'))
  .filter(function(f){ return /\.woff2$/.test(f); })
  .sort().map(function(f){ return 'fonts/'+f; });
var files=[].concat(
  ['js/data/registry.js','js/gen/core.js'],
  list('js/data',['registry.js']),
  list('js/gen',['core.js']),
  ['js/store.js','js/fx.js','js/ability.js','js/learn.js','js/plan.js','js/clock.js','js/predict.js',
   'js/charts.js','js/game.js','js/quests.js','js/modes.js','js/share.js',
   'js/i18n.js','js/runner.js','js/ui.js','js/ui-pages.js','js/map.js','js/research.js','js/stats.js','js/boot.js']
);
var tags=files.map(function(f){ return '<script src="'+f+'?v='+v+'"></script>'; }).join('\n');
var block='<!-- SCRIPTS:start — generated by tools/build-index.js, do not edit by hand -->\n'+tags+'\n<!-- SCRIPTS:end -->';

if(/<!-- SCRIPTS:start[\s\S]*?<!-- SCRIPTS:end -->/.test(html)){
  html=html.replace(/<!-- SCRIPTS:start[\s\S]*?<!-- SCRIPTS:end -->/, block);
} else {
  html=html.replace(/<!-- content:[\s\S]*<script src="js\/boot\.js[^"]*"><\/script>/, block);
}
html=html.replace(/css\/app\.css\?v=\d+/, 'css/app.css?v='+v);
fs.writeFileSync(path.join(ROOT,'index.html'), html);

/* keep the offline cache list and its version in step */
var sw=fs.readFileSync(path.join(ROOT,'sw.js'),'utf8');
var IMG=fs.readdirSync(path.join(ROOT,'img'))
  .filter(function(f){ return /\.(png|svg)$/.test(f); })
  .sort().map(function(f){ return 'img/'+f; });
var core=["'./'","'./index.html'","'./manifest.webmanifest'","'./css/app.css'"]
  .concat(FONTS.map(function(f){ return "'./"+f+"'"; }))
  .concat(IMG.map(function(f){ return "'./"+f+"'"; }))
  .concat(files.map(function(f){ return "'./"+f+"'"; }));
sw=sw.replace(/var CORE = \[[\s\S]*?\];/, 'var CORE = [\n  '+core.join(',\n  ')+'\n];');
sw=sw.replace(/var CACHE = '(?:iceskep|drakkhak)-v\d+';/, "var CACHE = 'drakkhak-v"+v+"';");
fs.writeFileSync(path.join(ROOT,'sw.js'), sw);
console.log('index.html: '+files.length+' scripts, '+FONTS.length+' fonts, version '+v);
